var savedAIContent = "";

var loadedAIContent = "";

function loadAIData()
{
    var fileData = localStorage.getItem("content");
    if(fileData != null)
    {
        /*
        If a story was loaded
        */
        console.log("HERE WE AEW");
        loadedAIContent = fileData;

    }
    else{
        /*
        If a new story was created
        */
        var instruct = "Welcome to Your Story! Here we will put in the story generated by the AI."
        loadedAIContent = instruct;
        console.log("HERE WE AEWn't");
    }
}

// source code:  https://github.com/cometchat-pro-tutorials/jquery-chat-app
const chatService = function() {
   $('#empty-chat').hide();
   $('#group-message-holder').hide();
   $('#loading-message-container').hide();
   $('#send-message-spinner').hide();

    loadAIData();

   let messageArray = [
       {
           username: "User",
           message: "This is a new message"
       },
       {
           username: "AI",
           message: loadedAIContent
       }
   ];

   if (messageArray.length < 1) {
       $('#empty-chat').show();
       $('#group-message-holder').hide();
   } else {
       $('#group-message-holder').show();
   }

   return {
	   fetchMessages: function() {
           $.each(messageArray, function(index, value) {
               let messageList;
               if (value.username !== "User") {
                   messageList = `
<div class="received-chats old-chats">
<div class="received-chats-img">
<img src="./Images/Logo.png" alt="AI" class="avatar">
</div>
<div class="received-msg">
<div class="received-msg-inbox">
<p>
<span id="message-sender-id">${value.username}</span><br />
                               ${value.message}
</p>
</div>
</div>
</div>
                   `
               } else {
                   messageList = `
<div class="outgoing-chats old-chats">
<div class="outgoing-chats-msg">
<p>${value.message}</p>
</div>
<div class="outgoing-chats-img">
<img src="./Images/Logo.png" alt="" class="avatar">
</div>
</div>
`
               }
               $('#group-message-holder').append(messageList);
           });
           this.scrollToBottom();
},
sendMessage: function(message){
    $('#send-message-spinner').show();
    // console.log("MEssage is: " + message.message);
    // savedAIContent = savedAIContent + message.message  + " ";
    messageArray.push(message);
    return true;
},
onMessageReceived: function() {
    $('#empty-chat').hide();
    //console.log("1");
    $('#group-message-holder').show();
    //console.log("2");
    $('#send-message-spinner').hide();
    //console.log("3");
    $.each(messageArray, function(index, value) {

        let messageList;
        if (value.username !== "User") {
            messageList = `
<div class="received-chats old-chats">
<div class="received-chats-img">
<img src="./Images/Logo.png" alt="AI" class="avatar">
</div>
<div class="received-msg">
<div class="received-msg-inbox">
<p>
<span id="message-sender-id">${value.username}</span><br />
                        ${value.message}
</p>
</div>
</div>
</div>
            `

         /*
            Here we want to save the AI message to the content so we can save it
         */

            
            if(value.username != "User")
            {
                console.log("message from: " + value.username);
                console.log("Message from AI: " + value.message);
                savedAIContent +=  value.message  + " ";
    console.log("CHECKING: " +  savedAIContent);
            }
    
        } else {
            console.log("Message from USER: " + value.message);
            messageList = `
<div class="outgoing-chats ongoing old-chats">
<div class="outgoing-chats-msg">
<p>${value.message}</p>
</div>
<div class="outgoing-chats-img">
<img src="./Images/Logo.png" alt="" class="avatar">
</div>
</div>
`
        }
        $('#group-message-holder').append(messageList);
    });
    this.scrollToBottom();
},
       scrollToBottom() {
           const chat = document.getElementById("msg-page");
           chat.scrollTo(0, chat.scrollHeight + 30);
       }
       
   }

}

();


function saveYourStory()
{
  
    //var userInput = document.getElementById("myText").value;
   
    
    console.log("SAVED: " + savedAIContent);

    // for(var index in messageArray)
    // {
    //     console.log("This is " + index);
    // }


    var pom = document.createElement('a');
    pom.setAttribute('href', 'data:text/plain;charset=utf-8,' + encodeURIComponent(savedAIContent));
    pom.setAttribute('download', "Your Story Saved");

    if (document.createEvent) {
        var event = document.createEvent('MouseEvents');
        event.initEvent('click', true, true);
        pom.dispatchEvent(event);
    }
    else {
        pom.click();
    }


    // var dataURI =  "data:application/octet-stream," + encodeURIComponent(savedAIContent);
    
    //  newWin = window.open(dataURI, 'Downloads');


    // var blob = new Blob([userInput], { type: "text/plain;charset=utf-8" });
    // saveAs(blob, "Test.txt");

}




